### ISSUE TITLE
client P2P connection closed (os error 10060)/error connecting to peer(os error 10061)

### ISSUE THREAD

**Issue by kishortungal** [input-output-hk/shelley-testnet#108]
**Describe the bug

When start the ./jormungandr i'm getting attached error.

** Prerequisites information
1. `jcli --full-version` output;
1. `jormungandr --full-version` output;
1. What is your Operating system? Windows 10
1. What version of the jormungandr node are you using? jormungandr-v0.5.6-x86_64-pc-windows-gnu
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)? No

**Expected behavior
Expect it to Run

![Capture](https://user-images.githubusercontent.com/55906020/66533328-2bc9ed00-ead8-11e9-9485-405e4020e028.PNG)

**Comment by carl-IOHK** [comment]
@kishortungal would you mind if we move this issue to the Support Portal? That way we can link it to the root casue issue and keep track of it better. To do that you could create a ticket here https://iohk.zendesk.com/hc/en-us/requests/new and drop note in this ticket with the ticket number. I would do it for you but I cannot since I do not have your email address.

**Comment by carl-IOHK** [comment]
Hi @kishortungal looks like your issue was resolved by the latest release https://github.com/input-output-hk/jormungandr/releases/tag/v0.6.0 can you please try that and let us know if your issue is resolved?

**Comment by kishortungal** [comment]
Hi,

Thanks for following up. My issue has been resolved.

Thanks,
Kishor
