### ISSUE TITLE
Rejected:       reason: "Error or Invalid account: Account does not exist"

### ISSUE THREAD

**Issue by cloudy-brain** [input-output-hk/shelley-testnet#12]
![Screenshot from 2019-06-22 12-42-42](https://user-images.githubusercontent.com/8825017/59963478-54a78180-94eb-11e9-8246-c97455e0cab8.png)

Start node in BFT mode from bootstrap. Run ./create-account-and-delegate.sh

Wait for a block to get added to blockchain. 

Checked the nodes log, but seems like the delegation utxo was rejected as it couldn't find the account?

I expected there to be 990 in the delegation part.

**Comment by disassembler** [comment]
delegation is only in genesis. If you start a node in BFT node you won't have Shelley features.

**Comment by dorin100** [comment]
Hi @cloudy-brain . What you see is that the script tries to delegate an Account Address that was not yet accepted by the blockchain (it was not included yet in a block). In order to see this working in Genesis mode, you can try to add some big timeouts (30-60s) after Account Creation and Transaction for sending money from the Faucet. This way we try to make sure that the Account was included already in a block (and has funds) before trying to delegate its stake.

So your expectation is correct, but in this case, you experience something specific to Genesis-Praos where the slot_duration is constant but the frequency of creating blocks is not stable since the creation of blocks is now a probability linked to the stake and active slot coefficient.

Furthermore, it would be much straight forward if you would run the same script in BFT mode where the blocks are created at a stable rate (so it is simpler to know when the next block is created and the script should really work out of the box).

**Comment by dorin100** [comment]
Documentation was update - https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html
