### ISSUE TITLE
Creating new account

### ISSUE THREAD

**Issue by altcoiner** [input-output-hk/shelley-testnet#24]
when I created new account, got the below message.
 
**Describe the bug**
jor-test/self_node$ jcli rest v0 account get ta1skjhw0frtf780fdgwfyda9g2s2jd3qtcgh5p9kmv7tqtf000a8nnx2cn8fs -h "http://127.0.0.1:8443/api"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Status(404), "http://127.0.0.1:8443/api/v0/account/a5773d235a7c77a5a87248de950a82a4d8817845e812db6cf2c0b4bdefe9e733")', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by dorin100** [comment]
Hi @altcoiner .

Address creation operation is not written in a block. Only the transaction is. This means that the blockchain would know about an Address only after it was included in a transaction.  

In order to validate that the Address you created is ok and that exists, you can use `jcli address info <ADDRESS>`

The command you are trying will return meaningful data only after you will include it in 1 transaction.

It is also true that the actual message is not very user-friendly but once we move further to more nodes, wallets, etc, this scenario will not be accessible anymore to the end users.

**Comment by dorin100** [comment]
Closing it as there are more than 3 days from the last interaction. Please reopen it if any clarification is required.
