### ISSUE TITLE
 "create-account-and-delegate.sh" does not work

### ISSUE THREAD

**Issue by btbf** [input-output-hk/shelley-testnet#25]
**Describe the bug**
Display different from wiki, does not advance to "3. now create a transaction and sign it"

**To Reproduce**
1. Go to './create-account-and-delegate.sh'
2. Display different from wiki

Is this correct?
[create-account-and-delegate.log](https://github.com/input-output-hk/shelley-testnet/files/3342607/create-account-and-delegate.log)

**Expected behavior**
Irregular should be avoided

**Additional context**
OS：Windows using WSL（Ubuntu 18.04 TLS）

**Comment by dorin100** [comment]
@btbf I cannot understand what exactly is the issue here. Can you help us with more details like - what are the exact steps you did and what is the expected result vs actual result? Thank you.

PS: you can find an explained delegation example also here: https://github.com/input-output-hk/shelley-testnet/wiki/How-to-delegate-from-a-new-account

**Comment by dorin100** [comment]
@btbf we also updated the delegation script in order to make sure that we are waiting that the transactions were included into blocks. Please make sure you use the latest versions of bootstrap and delegation scripts (https://github.com/input-output-hk/jormungandr/blob/master/scripts/create-account-and-delegate.shtempl)

**Comment by dorin100** [comment]
Closing it as there are more than 3 days from the last interaction. Please reopen it if any clarification is required.
