### ISSUE TITLE
More detail step for delegate and new account

### ISSUE THREAD

**Issue by altcoiner** [input-output-hk/shelley-testnet#28]
**USER STORIES**
I have tried to do making delegation according video(https://www.youtube.com/watch?reload=9&v=cr4vTPPE8ps&feature=youtu.be), but I think there are some procedures skipped and video is very in short.

**IMPROVEMENT PROPOSAL**
Please give us more detail guidance.

**Comment by dorin100** [comment]
Hi @altcoiner . You are right the video was made some time ago and it does not include the latest code changes/functionalities. 

In the meantime, we improved the `bootstrap `and `create-account-and-delegate.sh` scripts in order to automatically wait for the creation of new blocks (ensure that the transactions are included in a new block) before executing further operations. This means that in order to check the delegation functionality you need to: 

1. use the latest version of the node/bootstrap script/create-account-and-delegate script
2. start node using `bootstrap `script and execute `create-account-and-delegate.sh` script as in here: 
https://github.com/input-output-hk/shelley-testnet/wiki/How-to-delegate-from-a-new-account

@elviejo79 - FYI in case you decide we need to update the video.

**Comment by dorin100** [comment]
Detailed step-by-step scenario provided above.
