### ISSUE TITLE
JCLI (v0.5.2) ignores the '--testing' parameter.

### ISSUE THREAD

**Issue by ilap** [input-output-hk/shelley-testnet#54]
**Describe the bug**
The "jcli address account --testing ed25519_pk1.....' generate 'ca1' address instead of a 'ta1...' one.

**To Reproduce**

``` bash
$ jcli key generate --type=Ed25519Extended > esk.key
$ cat esk.key | jcli key to-public > pk.key
$ jcli address account --testing `cat pk.key`
ca1skyaq4xkd4l2nt790vh4ze29n7m8srkzqapaw666phxalssvn22ckknufpz
```

**Expected behavior**
It should definitely come back /w a 'ta1' address.

**Additional context**
It's an armv7l architecure and using the following [official binary](https://github.com/input-output-hk/jormungandr/releases/download/v0.5.2/jormungandr-v0.5.2-armv7-unknown-linux-gnueabihf.tar.gz)

**Comment by rinor** [comment]
No, it is correct. It shouldn't start with `ta` by default even if discrimination is **testing**.
It was changed a while ago since it was not necessary. The discrimination is encoded within the address.
You can verify that by issuing:
```
jcli address account --testing `cat pk.key`
```
and
```
jcli address account `cat pk.key`
```
Even though you are using the same public key the addresses will be different depending on discrimination. (check ca1**s**.... vs ca1**q**...) and the checksum (last 6 chars)

however if you want to have `ta` prefix you can use
```
jcli address account --prefix ta `cat pk.key` --prefix ta
```

**Comment by ilap** [comment]
`It was changed a while ago since it was not necessary.`

Thx for the info I did not know that and was in the impression, based on the old read of the spec, that the 'ca' hrp will be used for mainnet while the 'ta' for the testnet.

`The discrimination is encoded within the address.`

Yes, it's well known, but I was asking about the HRPs as the `hrp` in Bech32 are meant to be for humans e.g. distinguish between between the keys (ed25519_sk/pk etc.) and between the addresses (ca/ta). 
So, the users won't be able to distinguish between the testnet/mainnet addresses without using some tool, which will, IMO,  lead a lot of confusion to the users. 
That's why Bitcoin uses the __tb__ and __bc__ hrp for their SegWit addresses.

**Comment by jakewyo** [comment]
Hi @ilap you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by carl-IOHK** [comment]
@ilap I share your concern maybe the way to move this ahead would be to make a feature request on [jormungandr](https://github.com/input-output-hk/jormungandr/issues/new?template=jip.md). As far as the shelly testnet repo is concerned though, since you have clarification on your issue would it be OK to close this issue?

**Comment by ilap** [comment]
Yes, you can close it, but jcli should use `ta` hrp for test addresses as it's stated in the [design implementations decisions](https://github.com/input-output-hk/implementation-decisions/blob/master/text/0001-address.md#guide-level-explanation).
