### ISSUE TITLE
Wiki install instructions linux without environment variables

### ISSUE THREAD

**Issue by josefcoap** [input-output-hk/shelley-testnet#57]
Following the instructions I see that jcli or jormungandr are not in PATH variable. I can solve it, but think that post people following this instructions can be loss.

I propose guide a little more:
Create a folder: mkdir ada-node 
Get last version like: wget jormungandr.0.5.2.....
Unzip it: tar -zxvf 
Add environment variables: source $PATH...

on this way everyone knows that in linux the node is always on this dir and the jcli is executable in the system

**Comment by embraceitandfaceit** [comment]
Hello I agree with some more additional steps like: tar -zxvf filename to unzip the .gz file because I am a codingnoob with very basic knowledge of Linux and it would be an enormous help if these smaller steps would be included. Devs should realize that a lot of cardano supporters aren't necessarily technically apt but are still willing to go the distance but need guidance along the way. That being said, thank you for showing me the step of "tar -zxvf", was stuck here :-)

I initially tried to unzip the .gz file with the command gunzip

**Comment by josephj11** [comment]
Expanding the instructions as suggested here would be helpful.

**Comment by jakewyo** [comment]
Hi @josefcoap you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by dorin100** [comment]
Hi @josefcoap . Thank you for the details. We improved the documentations both for [Linux/macOS](https://iohk.zendesk.com/hc/en-us/articles/360036898153-How-to-install-Jormungandr-Networking-Linux-macOS-) and [Windows](https://iohk.zendesk.com/hc/en-us/articles/360036898353-How-to-Install-Jormungandr-Networking-Windows-)

Please let us know if these are ok in order to close this issue. Thank you!
