### ISSUE TITLE
"Example of genesis file" does not work

### ISSUE THREAD

**Issue by j-mueller** [input-output-hk/shelley-testnet#6]
**Describe the bug**

When running `jcli genesis encode` with the example file from https://input-output-hk.github.io/jormungandr/advanced/02_starting_bft_blockchain.html, the process fails with

```
genesis file corrupted
  |-> blockchain_configuration.consensus_leader_ids[0]: Failed to parse bech32, invalid data format at line 10 column 7
```

**To Reproduce**
1. Go to https://input-output-hk.github.io/jormungandr/advanced/02_starting_bft_blockchain.html
2. Copy the file in "Example of genesis file" and save it to `genesis.yaml`
3. Run `jcli genesis encode --input genesis.yaml --output block-0.bin
` (as described in the next section "Creating the block 0"

**Expected behavior**

`jcli` should produce a file `block-0.bin` (ie., it should be possible to run the example without errors)

**Additional context**

I built the version tagged v0.2.1 from source in `nix-shell`.

**Comment by dorin100** [comment]
Hi @j-mueller . That is only an example. Even so, it is not well documented how to fully configure the genesis.yaml file.

Until that would be improved, and in order for you to be able to continue with the node, please run the bootstrap script (https://github.com/input-output-hk/jormungandr/blob/master/scripts/bootstrap) in order to generate all required files in order to start a node.

**Comment by dorin100** [comment]
I opened a separate issue in order to have the documentation improved on how to start a node - https://github.com/input-output-hk/jormungandr/issues/515

**Comment by j-mueller** [comment]
OK, thanks for the pointer and for opening the ticket.
