### ISSUE TITLE
cannot run Jormungandr Networking node

### ISSUE THREAD

**Issue by jdalber** [input-output-hk/shelley-testnet#63]
I have followed step by step the guide: How to Install Jormungandr on Windows?
But I receive the message: cannot read the node configuration file
I have tried to change the indexation and the config file itself but nothing works, I can not figure out what is happening.
Attached PowerShell Error Message and last config file.
![PowerShellMessage](https://user-images.githubusercontent.com/55958771/65837968-eaa53200-e2ba-11e9-880e-5889bca71c60.png)
[node-config.txt.txt](https://github.com/input-output-hk/shelley-testnet/files/3667971/node-config.txt.txt)

**Comment by LeaderOfChampions** [comment]
The documentation is missing the **./** in front of that line, add ./ and it should kick-off for you.

`./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info`

**Comment by jdalber** [comment]
it works, although it seems can not connect to the bootstrap peer
thanks a lot! best regards.

**Comment by jdalber** [comment]
![PowerShell](https://user-images.githubusercontent.com/55958771/65838976-1548b800-e2c6-11e9-88d9-8a6409db0879.png)

**Comment by josephj11** [comment]
I ran into this exact issue in Linux and got past it by adding the `./` in front of the three occurrences of `jcli`.

**Comment by dorin100** [comment]
@jdalber - your node seems to be working as expected. Can you please take a look at this page - https://github.com/input-output-hk/shelley-testnet/wiki/How-do-I-know-that-my-node-is-in-%60sync%60 and let me know if your node receives blocks?

I see that `jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info` worked for you, right?

**Comment by jdalber** [comment]
adding the command "./" is what I missed, the complete line I used:
./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
Now I have created the public/private keys and requested the tokens from the faucet right. 
However I think it do not receive blocks. When calling for:
./jcli rest v0 node stats get --host "http://127.0.0.1:9000/api"
it received a failed request: could not connect with node, the receiver computer deny this connection.
Thanks
![PowerShell](https://user-images.githubusercontent.com/55958771/65885914-a9635f80-e358-11e9-9110-a62789dd3574.png)
![PowerShell2](https://user-images.githubusercontent.com/55958771/65885930-ae281380-e358-11e9-8a77-3df6b01f9efd.png)

**Comment by dorin100** [comment]
@jdalber - I updated the wiki file to highlight that you should update the `9000` port no with the one you used when started the node (inside node config).

**Comment by jdalber** [comment]
I updated the port to 3101 as noted in the node-config file, using the line:
./jcli rest v0 node stats get --host "http://127.0.0.1:3101/api"
but the system already can not connect with the node.
![PowerShell](https://user-images.githubusercontent.com/55958771/65892169-12e86b80-e363-11e9-9079-ff5cf62edfda.png)

**Comment by jdalber** [comment]
both requests to the node (get $ and stats) are denied. 
here we have a communication problem
![PowerShell](https://user-images.githubusercontent.com/55958771/65908649-17714c00-e384-11e9-8c97-1e1e13492a18.png)

**Comment by dorin100** [comment]
@jdalber - please follow the below steps and add both results this issue:
1. start the node and wait for some incoming connections - add the logs of the node here
2. after letting the node running for at least 3 minutes, execute the below command (please make sure you are using the rest port configured in node-config file) - add the output of the below command to your comment
```
jcli rest v0 message logs --host "http://127.0.0.1:3101/api"
```

**Comment by jdalber** [comment]
Hi, thanks
1. starting the node with: ./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770 --log-level=info
I received the error "gossip subscription stream failure"
![PowerShell](https://user-images.githubusercontent.com/55958771/65966846-e7768700-e41d-11e9-8260-ad457d5c1e82.png)
2. Requesting the logs with: ./jcli rest v0 message logs --host "http://127.0.0.1:3101/api"
(config file "rest: listen: "127.0.0.1:3101") received the error message "enable to make the request"
![PowerShell3](https://user-images.githubusercontent.com/55958771/65967096-450ad380-e41e-11e9-94f9-aee8e69987a8.png)

**Comment by dorin100** [comment]
Interesting. Can you please share also the content of the node-config.yaml that you used?

**Comment by jdalber** [comment]
yes, sir
![node-config](https://user-images.githubusercontent.com/55958771/65968096-e6465980-e41f-11e9-9ebe-e2ad563e16a4.png)

**Comment by dorin100** [comment]
Strange. I was also informed that for the moment there are multiple issues that the dev team is working on and also that one of the few ways of having the node working is to:
1. use your public ip address for `public_address`
2. open the port (3100 in your case) on the windows firewall
3. configure port forwarding on the router for port 192.168.192.55:3100

If the above steps are too complex, I suggest waiting for a new release, with the hope that most of the important bugs will be fixed. 

Thank you for your patience and support.

**Comment by GeorgeAris** [comment]
Hey guys, echoing these issues, the bigger problem is that there are a ton of documentation errors probably because things are changing so rapidly. For example, your instructions on creating a stake pool: 
$ jcli certificate new stake-pool-registration \
    --kes-key $(cat stake_pool_kes.pub) \
    --vrf-key $(cat stake_pool_vrf.pub) \
    --serial 1010101010 > stake_pool.cert

returns the following error: 
error: The following required arguments were not provided:
    --owner <PUBLIC_KEY>...
    --start-validity <SECONDS-SINCE-START>
    --management-threshold <THRESHOLD>

I think I can guess the first part, but not the rest. I am perhaps not your target market because I'm not too a dev, but if the goal is more testers, it would be great if someone consistently went through the instruction guides line by line for each release to update them. Could be a very junior person that does this and it would help adoption immensely.

**Comment by rdlrt** [comment]
@GerogeAris, not sure how that relates to this particular issue, but the documents for creating stakepool are below, and they dont refer to example/syntax you mention. Could you be checking an older documentation?
1. Script
ttps://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool-using-script
2. Manually
https://github.com/input-output-hk/shelley-testnet/wiki/How-to-create-a-Stake-Pool-manually

**Comment by GeorgeAris** [comment]
@rdlrt - relevant because OP's several addressed issues in this thread were also experienced by me in addition to what I posted. I am not concerned with just the example I posted but that a naive user coming to what seems to be an intro to testnet portal: https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-stake-distribution/

is led to many small errors, even omissions in steps in trying to set up testnet, so that it becomes much harder to do so. 

In my example that page leads directly to: 

https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake_pool.html#creating-your-stake-pool-certificate

which includes the instructions from my example, and errors out. 

I am not trolling or insulting your great work, but often the intro/tutorial/doc/onboarding processes get a bit neglected by devs since they don't actually do them everyday (since they don't have to after being set up) and I suspect this is what may be happening. I could surely be wrong, but that's the impression based on dozens of errors in the docs, from syntax, to non current doc links, to missing steps. 

I am simply trying to communicate to the powers that be that someone dedicated to actually doing the intro steps as a matter of course, and following the links on each page to make sure everything is current and correct, would vastly improve the quality of those docs and thus adoption. 

I am certainly not offended if you do not agree, I merely want to help as a user.

**Comment by rdlrt** [comment]
Totally understood, just trying to point you to correct documentation, so that your input can be linked correctly :) Would be great to have feedback on current documentation links sent above :)

**Comment by GeorgeAris** [comment]
yes, I appreciate that, thank you

**Comment by GeorgeAris** [comment]
@rdlrt just a heads up, running chrome on windows 10, 'save link as' for the scripts, executed per the directions you linked, downloads an HTML doc (which does not match the .SH code if you left click into the script in git). Have repeated several times and gotten same result. 

Instead I cut paste from the code snippet viewed on the Git site and 'save as' into same directory.

**Comment by jakewyo** [comment]
Hi @jdalber you may want to download and try the latest version if you have not yet done so: https://github.com/input-output-hk/jormungandr/releases/tag/v0.5.6

**Comment by jdalber** [comment]
Thanks for the support. 
I have downloaded the new version of jormungandr 5.6.
And I followed the steps 1-5. The node started running and the PowerShell log was the same as shown in step 5 of the guide. 
But in the step 6, checking the synch of the node I received an error message: 
"Failed to make a request, cannot connect with node, receiver node deny connection"
The host in the node-config file is 127.0.0.1:3101.
This is the same issue with previous versions. 

![PowerShell56](https://user-images.githubusercontent.com/55958771/66431673-ab24c700-e9d9-11e9-83d3-bab534d4d950.png)
![image](https://user-images.githubusercontent.com/55958771/66431911-32723a80-e9da-11e9-8dca-cf950c129b57.png)

**Comment by dorin100** [comment]
Hi @jdalber. I updated [this tutorial](https://iohk.zendesk.com/hc/en-us/articles/360036459274) in order to make it clear when the node is started. You can interact with the node (through `jcli` commands) only after the node was started. 

Can you please give it a try and let us know the result? Thank you for your patience!

**Comment by jdalber** [comment]
I continue to receive the same communication error log because the receptor node deny the connection.
Besides it takes too long to start the node.
Observe the WARN logs that should not be there, in the second file attached.

![PowerShell56](https://user-images.githubusercontent.com/55958771/66504112-b6cdc780-ea85-11e9-97fc-00fd0850e4bf.png)
![PowerShell56_ii](https://user-images.githubusercontent.com/55958771/66504119-bb927b80-ea85-11e9-8d98-b824d277eeca.png)

**Comment by dorin100** [comment]
Hi @jdalber . The issue that you are facing now is explained here - https://iohk.zendesk.com/hc/en-us/articles/360036404114-How-to-check-that-your-node-is-in-sync and is tracked here https://github.com/input-output-hk/jormungandr/issues/860

I will close this ticket as the initial problem was resolved. We are actively working on fixing #860.
