### ISSUE TITLE
Generate an address (to receive funds)

### ISSUE THREAD

**Issue by LeaderOfChampions** [input-output-hk/shelley-testnet#87]
**Describe the bug
Unclear how to find, create or display a public key with PowerShell in Windows10.

![image](https://user-images.githubusercontent.com/35902449/66099439-244c9600-e564-11e9-96dc-033e8c3ec960.png)

Regarding the above, is that one command, multiple? I tried breaking the lines up, but some still error out. Do I have to put ./ in front of jcli every time I see it?

Am I supposed to do something with the below?
![image](https://user-images.githubusercontent.com/35902449/66099520-6c6bb880-e564-11e9-8903-4bb8deed5422.png)

**Comment by dorin100** [comment]
Hi @LeaderOfChampions . if you follow [this](https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-(--v0.5.0) tutorial, I see that there is specified that you should use `GitBash` in order to run those commands. 

Furthermore, there is also a link to a script you can use.

Please give it another try by using the provided instructions and let us know the results.

**Comment by cliffc2** [comment]
it's 3 commands, first line makes a secret key, from the secret key you get the public key, from the public key you get the account address. that ta1.... string is the account address
I put some of my notes for an osx install. you can use is as a reference.  
https://github.com/cliffc2/cliffnotes

**Comment by LeaderOfChampions** [comment]
Thank you @cliffc2 that helped.
