### ISSUE TITLE
Rest account get searches for wrong account

### ISSUE THREAD

**Issue by PacificGreen** [input-output-hk/shelley-testnet#92]
**Describe the bug
Created a new account with the script or manually.  Try to obtain tokens from faucet web page without success due to time out error.  Continue to check if tokens were ever delivered to new account using:
$ ./jcli rest v0 account get ca1s4xjpfsv60k2rc9k7vje3gmct5huughp30q4ajm8zx8xghfj3vlwg53xkul -h  "http://127.0.0.1:3101/api"
failed to make a REST request
  |-> node rejected request because of invalid parameters
  |-> http://127.0.0.1:3101/api/v0/account/4d20a60cd3eca1e0b6f32598a3785d2fce22e18bc15ecb67118e645d328b3ee4: Client Error: 404 Not Found

Clearly you can see that it is looking for an entirely different account that no longer exists.

** Prerequisites information

1. What is your Operating system?
Windows 10
1. What version of the jormungandr node are you using?
5.5
1. Did you use jormungandr installer (snap, chocolatey, brew, etc.)?
Binary
**To Reproduce
Make new account and successfully retrieve some tokens.  Delete that account.  Create another account and try to retrieve tokens.  Run rest account get.

**Expected behavior
As above error.

**Additional context
If there is some way to reference or find the account that it is searching for then please inform.  The node in question is online and synced.  
$ ./jcli rest v0 node stats get --host "http://127.0.0.1:3101/api"
---
blockRecvCnt: 591
lastBlockDate: "224.19427"
lastBlockFees: 0
lastBlockHash: e4aaf90d9552dee39849995a329f73808c9e608a218ace5eacd54d4581d6e879
lastBlockHeight: "51562"
lastBlockSum: 0
lastBlockTime: "2019-10-04T18:41:08+00:00"
lastBlockTx: 0
txRecvCnt: 2
uptime: 3512

$ ./jcli rest v0 message logs --host "http://127.0.0.1:3101/api"
---
- fragment_id: ddd082162135ba3a1bad849035999b5c0f0750bb6e076c6329caaad9cc3f9a58
  last_updated_at: "2019-10-04T19:01:50.908063300+00:00"
  received_at: "2019-10-04T19:01:50.908063300+00:00"
  received_from: Network
  status: Pending
- fragment_id: cad1eb42761c2a0e559328cab6912c2bed21e4053f172b57bfb8991fd3b48f24
  last_updated_at: "2019-10-04T18:49:25.378163100+00:00"
  received_at: "2019-10-04T18:49:25.378163100+00:00"
  received_from: Network
  status: Pending

$ cat node-config.yaml
log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/192.168.0.12/tcp/3100"
  public_address: "/ip4/my.pu.bl.ic/tcp/3100"
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high
rest:
  listen: "127.0.0.1:3101"

**Comment by rdlrt** [comment]
Account is not the same as address. The URL conversion is expected.
The reason you see 404 us because the address you query did not have funds (as seen by your jormungandr node) at the time. I see that you have 1234 as of writing this message. So if you retry the command, you will see the account with same URL and a balance.
Not having funds would be a result of either:
- Your node did not sync/receive latest blocks (if you check around, there are .. issues spread over few tickets - some with user understanding and some with the network :) ). Thus, a sent funds tx may not show up on your node. In this case, a restart of node makes it available as the bootstrap will download the latest state of blocks.
- (This may not apply to you , but for completion) You're expecting funds from faucet, but there were few outages where people did not receive requested funds.Thus, the balance remains 0 resulting in 404.

**Comment by PacificGreen** [comment]
I see the funds have arrived.  For all intensive purposes this can be closed.
