### ISSUE TITLE
incoming P2P connection error: Protocol(Error(Http2, Error { kind: Proto(PROTOCOL_ERROR) }))

### ISSUE THREAD

**Issue by Philluminati** [input-output-hk/shelley-testnet#94]
So i am running this on an manjaro system (arch linux)
Linux 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux

i am using jormungandr 0.5.5 and i downloaded a pre-compiled package from github. (jormungandr-v0.5.5-x86_64-unknown-linux-gnu.tar.gz)

i followed all the steps that are described here: 
https://github.com/input-output-hk/shelley-testnet/wiki/How-to-setup-a-Jormungandr-Networking--node-(--v0.5.0)

after waiting appr. 15 min, there was an warning (error?) appearing. (logs attached)
WARN incoming P2P connection error: Protocol(Error(Http2, Error { kind: Proto(PROTOCOL_ERROR) })), peer_addr: 127.0.0.1:39360, task: network

when i check with: ./jcli rest v0 node stats get --host "http://127.0.0.1:3101/api"
if the blockchain is syncing, i get blockRecvCnt: 0 (logs attached)

any ideas on how to fix this?

[log_starting_jormungandr.txt](https://github.com/input-output-hk/shelley-testnet/files/3693150/log_starting_jormungandr.txt)
[log_status_jcli.txt](https://github.com/input-output-hk/shelley-testnet/files/3693151/log_status_jcli.txt)

**Comment by rinor** [comment]
- Protocol_error, do not worry about it. It is just notifying you that a connection was made to your node and it does not conform the required protocol. It may be caused by different things like port/vulnerability scanners or someone trying to connect with telnet, for example, just to verify that the port is opened. You can reproduce that warning by trying yourself to connect with:
  - telnet 127.0.0.1 3100

- the node not syncing is another matter and has nothing to do with the first one. It is a known issue being worked right now and will be fixed soon.

**Comment by Philluminati** [comment]
hei cool! thank you for your quick and nice answer!
i will look forward for the fix. do you know in which issue i have to look to see the problem that is causing that error?

**Comment by rinor** [comment]
This one for example https://github.com/input-output-hk/jormungandr/issues/860
